services:
  db:
    image: postgres:13
    container_name: db
    restart: always #container reinicia se morrer
    ports:
      - 2345:5432
    env_file:
      - .env.test #configurar POSTGRES_USER, POSTGRES_PASSWORD e POSTGRES_DB
    volumes:
      - pg:/var/lib/postgresql/data

  ts_node_app:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: ts_node_app
    expose:
      - '5000'
    ports:
      - 5000:5000
    depends_on:
      - db # s√≥ sobe quando o postgres tiver no ar
    env_file:
      - .env.test #configurar DATABASE_URL
    command: npm run dev
volumes:
  pg: